### PR TITLE
EnumValues Corrected Through Compiler

### PR DESCRIPTION
**Pull request by JurjenRoels**

### CODE REVIEW

**Comment by JurjenRoels** [comment]
Hi Pavel,

My previous pull-request was the wrong version of the compiled grammar. I still have to figure out how to run tests on vendor directories in Laravel. Hopefully it will pass this time.

The output of my conversion file through the complied grammar is now the same as the one I edited manually.

Sorry for the 2 pull request.

Regards
Jurjen

**Comment by butschster** [comment]
Don't worry! Thank you for the PR!

**Comment by JurjenRoels** [comment]
I understand why the ref tests fail. I changed the keywords form ref to ref: but that is only for inline references. So I will revert that. Maybe I can figure out a way to allow for a column names like referenceProcessId to not fail.

I do not know yet why the table group fails.

**Comment by JurjenRoels** [comment]
Can test locally now, closing this pull request until done testing

**Pull request closed without merging**
